# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ps_pl_axi_test.xdc

# Block Designs: bd/ps_pl_axi_test/ps_pl_axi_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_pl_axi_test || ORIG_REF_NAME==ps_pl_axi_test} -quiet] -quiet

# IP: bd/ps_pl_axi_test/ip/ps_pl_axi_test_processing_system7_0_0/ps_pl_axi_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_processing_system7_0_0 || ORIG_REF_NAME==ps_pl_axi_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_pl_axi_test/ip/ps_pl_axi_test_PS_PL_AXI_0_0/ps_pl_axi_test_PS_PL_AXI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_PS_PL_AXI_0_0 || ORIG_REF_NAME==ps_pl_axi_test_PS_PL_AXI_0_0} -quiet] -quiet

# IP: bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/ps_pl_axi_test_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_axi_smc_0 || ORIG_REF_NAME==ps_pl_axi_test_axi_smc_0} -quiet] -quiet

# Block Designs: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/bd_6b75.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_1/bd_6b75_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_2/bd_6b75_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_3/bd_6b75_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_4/bd_6b75_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_5/bd_6b75_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_6/bd_6b75_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_7/bd_6b75_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_8/bd_6b75_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_9/bd_6b75_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_10/bd_6b75_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_11/bd_6b75_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_12/bd_6b75_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/ps_pl_axi_test/ip/ps_pl_axi_test_rst_ps7_0_50M_0/ps_pl_axi_test_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_rst_ps7_0_50M_0 || ORIG_REF_NAME==ps_pl_axi_test_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_processing_system7_0_0/ps_pl_axi_test_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_processing_system7_0_0 || ORIG_REF_NAME==ps_pl_axi_test_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_1/bd_6b75_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_5/bd_6b75_s00a2s_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_6/bd_6b75_sarn_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_7/bd_6b75_srn_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_8/bd_6b75_sawn_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_9/bd_6b75_swn_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_10/bd_6b75_sbn_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/bd_0/ip/ip_11/bd_6b75_m00s2a_0_ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/ooc.xdc

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_axi_smc_0 || ORIG_REF_NAME==ps_pl_axi_test_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ip/ps_pl_axi_test_rst_ps7_0_50M_0/ps_pl_axi_test_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_axi_test_rst_ps7_0_50M_0 || ORIG_REF_NAME==ps_pl_axi_test_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA_Prj/ps_pl_axi_test/ps_pl_axi_test/ps_pl_axi_test.gen/sources_1/bd/ps_pl_axi_test/ps_pl_axi_test_ooc.xdc
