domain_path: D:\FPGA_Prj\ps_pl_axi_test\vitis_workspace\AXI_platform\export\AXI_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
