# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/KAN/FPGA_Prj/KAN_V1/KAN_V1.srcs/sources_1/ip/layer0_coeff_in0_out3/layer0_coeff_in0_out3.xci
# IP: The module: 'layer0_coeff_in0_out3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/KAN/FPGA_Prj/KAN_V1/KAN_V1.gen/sources_1/ip/layer0_coeff_in0_out3/layer0_coeff_in0_out3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer0_coeff_in0_out3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/KAN/FPGA_Prj/KAN_V1/KAN_V1.srcs/sources_1/ip/layer0_coeff_in0_out3/layer0_coeff_in0_out3.xci
# IP: The module: 'layer0_coeff_in0_out3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/KAN/FPGA_Prj/KAN_V1/KAN_V1.gen/sources_1/ip/layer0_coeff_in0_out3/layer0_coeff_in0_out3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer0_coeff_in0_out3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
