# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/KAN/FPGA_Prj/KAN_V1/KAN_V1.srcs/sources_1/ip/layer1_coeff_in4_out0/layer1_coeff_in4_out0.xci
# IP: The module: 'layer1_coeff_in4_out0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/KAN/FPGA_Prj/KAN_V1/KAN_V1.gen/sources_1/ip/layer1_coeff_in4_out0/layer1_coeff_in4_out0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer1_coeff_in4_out0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/KAN/FPGA_Prj/KAN_V1/KAN_V1.srcs/sources_1/ip/layer1_coeff_in4_out0/layer1_coeff_in4_out0.xci
# IP: The module: 'layer1_coeff_in4_out0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/KAN/FPGA_Prj/KAN_V1/KAN_V1.gen/sources_1/ip/layer1_coeff_in4_out0/layer1_coeff_in4_out0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer1_coeff_in4_out0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
